import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kereya Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
       
            <Image src="/logoK.svg" alt="Yawa Logo" width={200} height={100} />
        
        <h1 className={styles.title}>
          Welcome to <a href="https:yawatechnologie.com">Kereya server !</a>
        </h1>

        <p className={styles.description}>
          A digital health solution for health for all{' '}
          <code className={styles.code}> by Yawa Technologie</code>
        </p>

      </main>

      <footer className={styles.footer}>
        <a
          href="https:yawatechnologie.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/logoK.svg" alt="Yawa Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
